### ISSUE TITLE
Tambahan

### ISSUE THREAD

**Issue by jhokam** [akmmp241/gudang-sortir#2]
- Email ga intok cuman kata spesial (misal hanya spasi atau titik " @gmail.com atau .@gmail.com"
- Email berisikan 6 sampai 30 karakter dan harus ada karakter alfabet atau huruf disana (![Screenshot (67)](https://user-images.githubusercontent.com/55783077/221384826-3245c5cb-3c44-45d7-8780-2d0489bc44ed.png))
- Email ga intok berisi nomer tok nek luwih seko 8 karakter (![Screenshot (68)](https://user-images.githubusercontent.com/55783077/221384931-3f57e2d9-11cd-4afe-9802-1aa3b62ef8ed.png)
)
- Domain di dalam email (aziz@gmail.com) sing @gmail.com ga intok dirubah kan fixed
- Karakter " ` " masih bisa dipakai ketika mendaftar dikolom nama lengkap
- Setelah mengisikan deskripsi dengan karakter " ` " saya tidak bisa menambahkan kategori barang lagi (![Screenshot (70)](https://user-images.githubusercontent.com/55783077/221385296-e0098599-9d4f-46fd-b8fc-5faa87e23a69.png)
)

Sementara iki sek wkwwkwk

**Comment by akmmp241** [comment]
- issue 1: **fixed**
- issue 2: tidak bisa di fix tapi bisa dibuat email minimal 6 huruf (namun tidak/belum diterapkan)
- issue 3: tidak bisa di fix 
- issue 4: tidak termasuk issue yang dapat menyebabkan masalah
- issue 5: **fixed** sekarang tidak bisa menginput " ` "
- issue 6: **fixed** issue 6 tidak berhubungan pada issue 5, namun sekarang sudah di fix
