### ISSUE TITLE
Review Fitur Baru

### ISSUE THREAD

**Issue by jhokam** [akmmp241/gudang-sortir#3]
1. Pada halaman barang deskripsi tidak opsional sehingga saya harus mengisinya (wajib)
2. Bug pada saat saya mengisi kolom tabel barang jika saya menginput kesalahan (barang sudah ada) nanti id barang akan menunpuk dari sebelumnya + 1 id tambahan baru
![Screenshot (72)](https://user-images.githubusercontent.com/55783077/221408149-53bd8f4b-264e-400f-8134-412806f35d22.png)

**_FIN_**

EDIT = mal tambahi versine dadi ono 3 format e ngene 00.11.22 (00 versi publish yen wes di publish) (11 versi beta dadi wes ono hasil front end e) (22 versi alpha sing jek dadi backend e kyk saiki) semisal gudang-sortir v0.0.23 (karena wes commit 23 kali) kan enak nek ngono wkkwkwk

**Comment by akmmp241** [comment]
**bikin versi ga semudah itu ngab**
### Semantic Versioning
[https://semver.org/](https://semver.org/)
baca ngab

**Comment by akmmp241** [comment]
- [ issue 1: deskripsi tidak opsional] **FIXED** `$request->getNamaBarang() == null || trim($request->getNamaBarang()) == ""` pada kode sebelumnya saya menambah kan validasi untuk deskripsi seperti ini `$request->getNamaBarang() == null || trim($request->getNamaBarang()) == "" || $request->getDeskripsi == null`
- [ issue 2: ] **FIXED** lupa untuk membuat baris kode ini `$id_barang = substr($id_barang, strlen($id_barang)-5);` ke setiap function di BarangController.php

**Comment by akmmp241** [comment]
btw sudah ada release tag nya ngab 👍
