### ISSUE TITLE
Bug lagi

### ISSUE THREAD

**Issue by jhokam** [akmmp241/gudang-sortir#4]
1. Pada saat user menambahkan barang, jika user menambah barang pada beda kategori, id barang akan terduplikasi dan urutan tidak sesuai yang diharapkan (barang masuk (baru) diatas lalu yang lama dibawah (LIFO)) atau (barang masuk (lama) diatas yang baru dibawah(FIFO))

# **Metode LIFO**
LIFO (Last In First Out) merupakan metode pengelolaan barang yang berkebalikan dengan FIFO. Manajemen persediaan dengan metode ini dilakukan dengan cara barang yang terakhir masuk ke gudang adalah barang pertama yang akan keluar dari gudang untuk dijual.

# **Metode FIFO**

FIFO (First In First Out) merupakan salah satu metode manajemen persediaan dengan cara memakai stok barang di gudang sesuai dengan waktu masuknya. Stok yang pertama kali masuk ke gudang adalah stok yang harus pertama kali keluar dari gudang.

**Comment by akmmp241** [comment]
**issue fixed**
di database di table barang di tambahkan colom id yang berisi nilai string angka seperti ini '00001' sehingga pengurutan pada table barang tidak perlu menggunakan colom id_barang dengan contoh nilai 'KMR-00001' karena dari data tersebut diurutkan berdasarkan alphabet yang ada di depan
