### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by jhokam** [akmmp241/gudang-sortir#5]
1. Bug pada saat saya mendaftar menggunakan email "aziz@.com" pada halaman register diterima namun saat saya login hal tersebut malah ditolak, sama halnya saya mendaftar menggunakan a@g.c masih bisa
![Screenshot (74)](https://user-images.githubusercontent.com/55783077/222320031-4b5d56b0-d5e2-4754-bb95-5a54a937cb5b.png)
2. Pada saat saya menambahkan karakter petik (") di kolom password (lama maupun baru) tanda petik (") hilang entah kemana
3. Saya mengisikan kolom ganti email dengan email berikut (a@g.c) jika email tidak valid maka email lansung ganti ke email sekarang (belum ganti email akun)
4. Email yang sudah terdaftar masih bisa di daftarkan
5. Email yang sebelumnya tidak boleh sama dengan email baru
6. Nama sebelumnya tidak boleh sama dengan nama baru

Sekian _Good Luck_

**Comment by akmmp241** [comment]
1. **Fixed issue 1**
2. **Fixed issue 2**
3. **Fixed issue 3**
4. **Fixed issue 4**
5. **Fixed issue 5**
6. **Issue 6 tidak perlu di fix (sudah sesuai)**
