### ISSUE TITLE
Bug-Bag-Bug

### ISSUE THREAD

**Issue by jhokam** [akmmp241/gudang-sortir#6]
![Screenshot (85)](https://user-images.githubusercontent.com/55783077/224693564-a0f7ba78-e5f8-40d0-9c77-f09b86d06ced.png)
![Screenshot (86)](https://user-images.githubusercontent.com/55783077/224693576-b08c0e3c-d93e-4cd3-9a29-496568acac6b.png)
- Itu terjadi setelah menginput data "Barang Masuk" tidak bisa dihapus, dihapus lewat barang atau kategori tetep tidak bisa

![Screenshot (87)](https://user-images.githubusercontent.com/55783077/224696068-5d2b1488-03dc-43f9-8a9f-6aceee907145.png)
- Dapat menduplikasi "Nama Kategori" melalui aksi edit

![Screenshot (88)](https://user-images.githubusercontent.com/55783077/224740562-b406876e-afb0-4cac-96ce-35c269dadc58.png)
- Nama Kategori tidak boleh mengandung karakter spesial padahal saya mengisikan form Nama Barang bukan Nama Kategori dan harusnya ini bisa sudah saya coba dengan tanda " ! " bisa namun dengan tanda " ` " tidak bisa

![Screenshot (89)](https://user-images.githubusercontent.com/55783077/224741731-fce5e873-12eb-434a-8ad8-69eaa0a90241.png)
- Nama Barang tidak boleh ada karakter spesial jika saya menggunakan tanda " ` " tidak bisa namun jika saya menggunakan tanda " ! " tanda seru malah bisa atau tanda " @ " et bisa

![Screenshot (90)](https://user-images.githubusercontent.com/55783077/224743838-0db44e5e-637f-4db7-bfab-7660c4f79fc5.png)
- Sama halnya dengan deskripsi di "Tambah Barang" tetep tidak bisa pakai " ` " namun masih bisa menggunakan " ! "

5 5 dulu aja kwkwkw

### _**gambarimas**_

**Comment by akmmp241** [comment]
### Issue Fixed
**all issue fixed**
